## v0.1

In [1]:
# CANDIDATES="spotify_candidates_v0.1"
# INITIAL_IDS="initial_ids_v0.1"
# Q_JUDGE_PROMPT="q_judge_v0.1"
# Q_EXTRACT_PROMPT="q_extraction_v0.1"
# A_EXTRACT_PROMPT="a_extraction_v0.1"

CANDIDATES = "spotify_candidates_v0.1"
INITIAL_IDS = "initial_ids_v0.1"
Q_JUDGE_PROMPT = "q_judge_v0.1"
Q_EXTRACT_PROMPT = "q_extraction_v0.1"
A_EXTRACT_PROMPT = "a_extraction_v0.1"
MODEL = "gpt-4o-mini-2024-07-18"

MIN_MATCH_RATE_Q = 0.9
MIN_MATCH_RATE_A = 0.9
MAX_A_LENGTH = 500 # words

OUTFILE = "../output/pipeline_results_v0.1.tsv"

### Run

In [2]:
import pandas as pd

input_file = f"../output/data/{CANDIDATES}.tsv"
q_extraction_file = f"../output/q_extraction/parsed/{MODEL}/{Q_EXTRACT_PROMPT}/{INITIAL_IDS}.tsv"
quality_eval_file = f"../output/q_quality/parsed/{MODEL}/{Q_JUDGE_PROMPT}/{INITIAL_IDS}.tsv"
a_extraction_file = f"../output/a_extraction/parsed/{MODEL}/{Q_JUDGE_PROMPT}/{A_EXTRACT_PROMPT}/{INITIAL_IDS}.tsv"

df_input = pd.read_csv(input_file, sep="\t")
df_q_extraction = pd.read_csv(q_extraction_file, sep="\t")
df_quality = pd.read_csv(quality_eval_file, sep="\t")
df_a_extraction = pd.read_csv(a_extraction_file, sep="\t")

In [3]:
df_full = (
    df_q_extraction
        .merge(df_quality, on="podcast_id", how="left")
        .merge(df_a_extraction, on="podcast_id", how="left")
        .merge(df_input, on="podcast_id", how="left")
)

In [4]:
df_full.columns

Index(['podcast_id', 'question', 'q_verbatim', 'match_rate_q', 'q_span',
       'reasoning', 'info_seeking', 'info_seeking_logprob', 'self_contained',
       'self_contained_logprob', 'response', 'answer', 'a_verbatim',
       'match_rate_a', 'a_span', 'text'],
      dtype='object')

In [5]:
### FILTERING:

df_keep = df_full.copy()
print(f"{df_keep.shape[0]} -- Start")

# See where q is not nan:
mask_ = df_keep['question'].notnull()
df_keep = df_keep[mask_]
print(f"{df_keep.shape[0]} -- Found question")

# See where match_rate_q > MIN_MATCH_RATE_Q:
mask_ = df_keep['match_rate_q'] > MIN_MATCH_RATE_Q
df_keep = df_keep[mask_]
print(f"{df_keep.shape[0]} -- Match rate Q > {MIN_MATCH_RATE_Q}")

# See where 'info_seeking'==yes, 'self_contained'==yes:
mask_ = (df_full['info_seeking'] == 'yes') & (df_full['self_contained'] == 'yes')
df_keep = df_full[mask_].copy()
print(f"{df_keep.shape[0]} -- Good Q")

# Where answer is not nan:
mask_ = df_keep['answer'].notnull()
df_keep = df_keep[mask_]
print(f"{df_keep.shape[0]} -- Found answer")

# Where answer is after the question:
df_keep[["a_span", "q_span"]] = df_keep[["a_span", "q_span"]].map(lambda x: eval(x))
mask_ = df_keep.apply(lambda x: x['a_span'][0] > x['q_span'][1], axis=1)
df_keep = df_keep[mask_]
print(f"{df_keep.shape[0]} -- Answer after Q")

# Where answer is not very long:
mask_ = df_keep['a_verbatim'].str.count(" ") < MAX_A_LENGTH
df_keep = df_keep[mask_]
print(f"{df_keep.shape[0]} -- Answer not too long")

# See where match_rate_a > MIN_MATCH_RATE_A:
mask_ = df_keep['match_rate_a'] > MIN_MATCH_RATE_A
df_keep = df_keep[mask_]
print(f"{df_keep.shape[0]} -- Match rate > {MIN_MATCH_RATE_A}")

# Where the Q appears just once in the original text:
mask_ = df_keep.apply(lambda row: row['text'].lower().count(row['q_verbatim'].lower()) > 1, axis=1)
df_keep = df_keep[~mask_]
print(f"{df_keep.shape[0]} -- Q appears once")

# # Where the Q is not a subset of the A (is already implied in answer after Q):
# mask_good_qa = df_tmp.apply(lambda x: x['question'].lower().strip() not in x['answer'].lower(), axis=1)
# df_tmp = df_tmp[mask_good_qa]
# print(df_tmp.shape)

60 -- Start
47 -- Found question
34 -- Match rate Q > 0.9
13 -- Good Q
13 -- Found answer
9 -- Answer after Q
8 -- Answer not too long
7 -- Match rate > 0.9
6 -- Q appears once

In [6]:
# See some examples:
pd.set_option('display.max_colwidth', 200)
df_keep[["question", "a_verbatim", "match_rate_q", "match_rate_a"]].sort_values("match_rate_a", ascending=False).head(20)

,question,a_verbatim,match_rate_q,match_rate_a
10,What are the advantages of staying or returning to Real Madrid?,What is clear is I want to play and not be sat on the bench,1.0,1.000000
44,"""Can guys and girls be friends when one of them catches feelings?""",no no no i'm in this predicament like kind of right now like the guy that i'm talking to kind of goes with the fuck what do you think yeah um i'm kind of talking to this guy right now and he's lik...,1.0,1.000000
58,"""Could you give us just a high level overview of a mining pool, what it is and what it does?""","Sure, sure, sure. So a mining pool basically is the only way nowadays that you can mine Bitcoin and major cryptos because of the difficulty. So the more hash power that is connected into the Bitco...",1.0,1.000000
50,"Is there anything cooler than a billion, though?","Well, what I find out is that a trillion is actually better than that",1.0,1.000000
59,What is the gut brain about?,"Well, the gut brain is, you know, we have so many more messages come from the guts to the rest of the body than even the brain sends out. You know, if you think about your gut as your biggest orga...",1.0,1.000000
21,"""Do you have any comments or advice regarding future pre-med applicants who either come from business or marketing or just kind of is transitioning right now?""","i would say really take time to reflect and decide, see why you want to do it. Are you just bored with your current job? Are you trying different jobs? Is it like a longer term life issue where y...",1.0,0.963855

In [9]:
# NOTE here I send the output to a text file and manually select the good IDs:
df_tmp = df_keep[["podcast_id", "q_verbatim", "a_verbatim", "match_rate_a"]].sort_values("match_rate_a", ascending=False)

df_tmp.to_csv(f"../output/tmp.tsv", sep="\t", index=False)
for i, row in df_tmp.iterrows():
    print(f"{row['podcast_id']}\t{row['q_verbatim']}\t{row['a_verbatim']}")

podcasts-audio/5/9/show_59h8QSNa9n0SsLDAdH2GAA/4eNkaKFM0Ex4dbiExiuHlX	What are the advantages of staying or returning to Real Madrid	What is clear is I want to play and not be sat on the bench
podcasts-audio/3/H/show_3hjcWPBEicA1JnECxejrIZ/1IGmgW2ussPLS7x3l7JtAC	can guys and girls be friends when one of them catches feelings	no no no i'm in this predicament like kind of right now like the guy that i'm talking to kind of goes with the fuck what do you think yeah um i'm kind of talking to this guy right now and he's like he's brought it to my attention that he has his best friend's a girl and you know she's made it a point that very clear that she has feelings for him so the thing in this situation is like it's just kind of tricky but the answer is just no like don't get yourself in that position because you're never gonna fucking win yeah it's his best friend you're not gonna fucking get it past him honestly if they're close enough like they're gonna end up together at some point so and if you say you are the friend like that you guys have like the friendship with then you catch feelings for him if you want to keep that friendship in any way, don't say anything. Don't say, yeah. Ask your friends, ask your friends to ask, like, hints, like, does he have feelings, and if they're like, no, don't say anything. Just, yeah, just kind of. You can still just be hurt in the end. Just silently move on. Yeah, it's just gonna piss one of you off, and then you're gonna, like, not end up being friends, so. No, it sucks, but, I mean, it is what it is. Yeah. You would rather keep the friendship than be heartbroken and lose your best friend. Yeah, so. Basically, don't get yourself in that position either way
podcasts-audio/2/C/show_2CLetGT20MFsHqfeBN3fYl/3EEivrpUk8v87BNaKjjXxz	could you give us just a high level overview of a mining pool, what it is and what it does	Sure, sure, sure. So a mining pool basically is the only way nowadays that you can mine Bitcoin and major cryptos because of the difficulty. So the more hash power that is connected into the Bitcoin network, the more difficulty increases in the Bitcoin network to maintain the 10 minute block time. So what happens is that mining evolved into everyone pulling their hash power and then getting a percentage of what you put into the mining pool. Number one, what this does is that it creates a more stable income. Like if you were mining by yourself, you might find a block every so often, right? But if you're mining with a big mining pool that has a lot of hash power, you'll probably find more blocks more often. So your income is more steady. That's what the mining pool does right that's the end i mean providing all those really good tools to make uh even more profitable we just came out with a bitcoin to a bitcoin cash auto switch feature so what that does is whenever we see that the price of bitcoin cash is high and the difficulty might be low and the miners will make more money if they switch to bch we do it automatically if you choose this feature so it's done automatically in the back end by us so what this does the miners actually even make more money if they switch to PCH. We do it automatically if you choose this feature. So it's done automatically in the backend by us. So what this does, the miners actually even make more profit. These types of features like the auto switch feature are what mining pools do, right? It increases the profitability of the miners and creates steady income
podcasts-audio/5/J/show_5JFugv0GD68SZC0Cuh1wXi/4eM1aRAeEDVZzxPv4Ko5DQ	Is there anything cooler than a billion, though	Well, what I find out is that a trillion is actually better than that
podcasts-audio/4/K/show_4kvJHO5LLxyfxbGPmAk2yQ/55kYxbeaCDVpnqwIe2Q225	what is the gut brain about	Well, the gut brain is, you know, we have so many more messages come from the guts to the rest of the body than even the brain sends out. You know, if you think about your gut as your biggest organ in your body, there's a lot going on in there. I forget the stats. I think it's like if you opened it up, it'd be a football pitch and it's seven metres long or something like that. Don't quote me. But there's a lot going on. And one of the common problems that we're seeing today, all of these lifestyle diseases, IBS, diverticulitis, Crohn's, you know, all of these debilitating illnesses that we're seeing today all of these lifestyle diseases you know ibs diverticulitis crones you know all of these debilitating you know illnesses that we're experiencing um even the whole debate around intolerances and things you know when the gut stops working food becomes intolerable there's so many
podcasts-audio/3/X/show_3XVVceNECAwk8xvSSYdgIO/7itwLRPH0t1ai26BTdztAA	do you have any comments or advice regarding future pre-med applicants who either come from business or marketing or just kind of is transitioning right now	 i would say really take time to reflect and decide, see why you want to do it. Are you just bored with your current job? Are you trying different jobs? Is it like a longer term life issue where you're looking back and saying, I want to do something meaningful with my life? Or is it just like you're feeling antsy about your current job right now? That's very different. And that's like something that only you will really know. Because once you get into this medical field and like if you do get in, but once you do get in, it's a long, long road. And so like you don't want to be flaky with your career. Like, you know, like that's another thing. that's something that came up when I was, that was some of the feedback that my advisors and my postbac said they were like you building your resume and building your application for this is not just checking boxes it's to show that you have long-term commitments and that you're not just going to flake on another career after you change your mind like you flaked on your marketing career are you going to flake again when you decide marketing medicine is too hard that's something that not everyone thinks about but you definitely don't want to have a flaky nature about your career and so that's something like i would say like advice really really reflect on why you want to do medicine and what you want your life to be like and then then also reflect on, do you fully understand how long this road is? Like I do because I see it with my dad and like I've been around people who are in the medical field. But once you do understand how long this road is, are you still interested? And then don't be afraid to just make the jump there are always going to be people who are supportive there are always going to be people who are doubting you i had so many doubters i had so many they're so annoying people are like oh like well it's kind of late isn't it like good luck like when are you going to get married and have kids like i don't know i'll do with that later like that's not something you need to worry about you need to worry about like um what is going to be fulfilling in your life long term and so yeah don't be afraid to make the jump there will always be people who are supportive and there is always going to be someone like more like out of nowhere like more older or more experienced or more whatever than you if you do decide to change. Like there are always people younger. There are always people older. Don't let that be a barrier to making a career decision

In [10]:
# The manually selected IDs:
good_ids = [
    "podcasts-audio/5/9/show_59h8QSNa9n0SsLDAdH2GAA/4eNkaKFM0Ex4dbiExiuHlX",
    "podcasts-audio/3/H/show_3hjcWPBEicA1JnECxejrIZ/1IGmgW2ussPLS7x3l7JtAC",
    "podcasts-audio/2/C/show_2CLetGT20MFsHqfeBN3fYl/3EEivrpUk8v87BNaKjjXxz",
    "podcasts-audio/5/J/show_5JFugv0GD68SZC0Cuh1wXi/4eM1aRAeEDVZzxPv4Ko5DQ",
    "podcasts-audio/4/K/show_4kvJHO5LLxyfxbGPmAk2yQ/55kYxbeaCDVpnqwIe2Q225",
    "podcasts-audio/3/X/show_3XVVceNECAwk8xvSSYdgIO/7itwLRPH0t1ai26BTdztAA",
]

In [14]:
### SAVE
df_to_save = (
    df_keep
    [["podcast_id", "question", "q_verbatim", "match_rate_q", "q_span",
      "answer", "a_verbatim", "match_rate_a", "a_span"]]
)
df_to_save = df_to_save[df_to_save["podcast_id"].isin(good_ids)]

# strip quotation marks from the strings:
str_cols = ["question", "q_verbatim", "answer", "a_verbatim"]
for col in str_cols:
    df_to_save[col] = df_to_save[col].str.strip("\"").str.strip()
df_to_save.to_csv(OUTFILE, sep="\t", index=False)

print(f"Saved {df_to_save.shape[0]} rows to {OUTFILE}")
df_to_save.head(2)

Saved 6 rows to ../output/pipeline_results_v0.1.tsv

,podcast_id,question,q_verbatim,match_rate_q,q_span,answer,a_verbatim,match_rate_a,a_span
10,podcasts-audio/5/9/show_59h8QSNa9n0SsLDAdH2GAA/4eNkaKFM0Ex4dbiExiuHlX,What are the advantages of staying or returning to Real Madrid?,What are the advantages of staying or returning to Real Madrid,1.0,"(3801, 3862)",What is clear is I want to play and not be sat on the bench.,What is clear is I want to play and not be sat on the bench,1.000000,"(3865, 3923)"
21,podcasts-audio/3/X/show_3XVVceNECAwk8xvSSYdgIO/7itwLRPH0t1ai26BTdztAA,Do you have any comments or advice regarding future pre-med applicants who either come from business or marketing or just kind of is transitioning right now?,do you have any comments or advice regarding future pre-med applicants who either come from business or marketing or just kind of is transitioning right now,1.0,"(47609, 47764)","For anyone who like thinks that they want to quit their job and go into a new career you mean, I would say really take time to reflect and decide, see why you want to do it. Are you just bored wit...","i would say really take time to reflect and decide, see why you want to do it. Are you just bored with your current job? Are you trying different jobs? Is it like a longer term life issue where yo...",0.963855,"(47867, 50396)"

--------------------------------------