In [2]:
# 8,0K    output/text_ir_dataset_v0.1/answers.tsv
# 7,6G    output/text_ir_dataset_v0.1/docs.tsv
# 4,0K    output/text_ir_dataset_v0.1/qrels.tsv
# 4,0K    output/text_ir_dataset_v0.1/queries.tsv

import pandas as pd

df_answers = pd.read_csv('../output/text_ir_dataset_v0.1/answers.tsv', sep='\t')
df_docs = pd.read_csv('../output/text_ir_dataset_v0.1/docs.tsv', sep='\t')
df_qrels = pd.read_csv('../output/text_ir_dataset_v0.1/qrels.tsv', sep='\t')
df_queries = pd.read_csv('../output/text_ir_dataset_v0.1/queries.tsv', sep='\t')

/tmp/ipykernel_763961/3523418562.py:9: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df_docs = pd.read_csv('../output/text_ir_dataset_v0.1/docs.tsv', sep='\t')

In [ ]:
print(f'{df_answers.shape=}')
print(f'{df_docs.shape=}')
print(f'{df_qrels.shape=}')
print(f'{df_queries.shape=}')

df_answers.shape=(6, 5)
df_docs.shape=(12854943, 7)
df_qrels.shape=(36, 4)
df_queries.shape=(6, 5)

In [3]:
df_answers.head(2)

,answer_id,text,podcast_id,start_word_idx,end_word_idx
0,5,"Well, the gut brain is, you know, we have so m...",podcasts-audio/4/K/show_4kvJHO5LLxyfxbGPmAk2yQ...,4881,5041
1,0,What is clear is I want to play and not be sat...,podcasts-audio/5/9/show_59h8QSNa9n0SsLDAdH2GAA...,723,738

In [4]:
df_docs.head(2)

,docid,text,podcast_id,start_word_idx,end_word_idx,original_text,masked_word_indices
0,46qer7i7xGnMQAQ8L3AhJa#0,"Drums, please! Drums, please-Note here. Welcom...",podcasts-audio/7/D/show_7DCBxMZp0bWUV6bCWdz2pm...,0,100,NaN,[]
1,46qer7i7xGnMQAQ8L3AhJa#1,"your emotional experience. And really, it's ju...",podcasts-audio/7/D/show_7DCBxMZp0bWUV6bCWdz2pm...,50,150,NaN,[]

In [6]:
df_queries.head(2)

,qid,text,start_word_index,end_word_index,podcast_id
0,0,What are the advantages of staying or returnin...,712,723,podcasts-audio/5/9/show_59h8QSNa9n0SsLDAdH2GAA...
1,1,be do you have any comments or advice regardin...,9061,9087,podcasts-audio/3/X/show_3XVVceNECAwk8xvSSYdgIO...

In [ ]:
df_qrels.head(2)

   qid                      docid      rel  answer_id
0    5  55kYxbeaCDVpnqwIe2Q225#96  0.11875          5
1    5  55kYxbeaCDVpnqwIe2Q225#97  0.43125          5

In [10]:
# Per query, avg rel and count:
df_qrels.groupby('qid').agg(
    avg_rel=('rel', 'mean'),
    n=('docid', 'nunique')
).sort_values('avg_rel', ascending=False)

      avg_rel   n
qid
0    1.000000   2
3    0.666667   3
5    0.400000   5
2    0.285714   7
4    0.250000   8
1    0.181818  11